# Generated by Django 2.2.4 on 2019-08-24 09:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('key', models.CharField(editable=False, max_length=10)),
                ('solved', models.BooleanField(default=False)),
                ('state', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ('-created',),
            },
        ),
    ]
