# Generated by Django 2.2.4 on 2019-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dectauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
